### ISSUE TITLE
Fails to load CSV with `INTERNAL Error: Missing DB manager`

### ISSUE THREAD

**Issue by alexkreidler** [duckdb/duckdb-wasm#1293]
### What happens?

Error:
```
Uncaught (in promise) Error: INTERNAL Error: Missing DB manager
    at Go.insertCSVFromPath (duckdb-browser-eh.worker.js:11:20117)
    at lc.onMessage (duckdb-browser-eh.worker.js:10:58309)
    at Qu.globalThis.onmessage (duckdb-browser-eh.worker.js:24:10976)
```

### To Reproduce

My code:
```ts
import { AsyncDuckDB } from "@duckdb/duckdb-wasm";
import arrow from "apache-arrow"
import { DuckDB } from "./duckdb";


export interface DuckDB {
    conn: duckdb.AsyncDuckDBConnection
    db: duckdb.AsyncDuckDB
}

export async function loadCSV(file: File, db: DuckDB) {
    console.log("Loading CSV file", file.name, db);
    
    await db.db.registerFileText(file.name, await file.text());
    console.log(await db.db.globFiles("*"));
    
    
    // ... with typed insert options
    await db.conn.insertCSVFromPath(file.name, {
        schema: 'main',
        detect: true,
        header: true,
        name: file.name.replace('.csv', ''),
    });

    console.log("Done Loading CSV file", file.name);

}
```
```
import { Button, Icon, Input, Stack } from "@chakra-ui/react";
import {CheckIcon} from "@chakra-ui/icons"
import { loadCSV } from "./loadCSVs";  
import { useDuckDB } from "./realDuckDB";
import { useState } from "react";
import { getSchema } from "./getSchema";

export const RunQuery = () => {
  const db = useDuckDB();
  const [loading, setLoading] = useState(false);
  const [done, setDone] = useState(false);
  const [file, setFile] = useState<File>(null)

  const handleFileUpload = (e) => {
    setFile(e.target.files[0])
  }
  const onSubmit = async (e) => {
    // setLoading(true);
    setDone(false);
    await loadCSV(file, db);
    setLoading(false);
    setDone(true);
    await getSchema(db)
  };

  return (
    <Stack spacing={4} direction="row">
      <Input type="file" onChange={handleFileUpload} />
      <Button isLoading={loading} onClick={onSubmit}>
        {done && <CheckIcon color="green.500"  />} 
        Upload CSV
      </Button>
    </Stack>
  );
};

```
Running with the vite wasm bundles.

Attach a file, click "upload", and see the error

### Browser/Environment:

Opera 101.0.4829.0 Chromium version:114.0.5735.9

### Device:

Windows LG PC

### DuckDB-Wasm Version:

1.27.0

### DuckDB-Wasm Deployment:

localhost

### Full Name:

Alex Kreidler

### Affiliation:

unaffiliated

**Comment by carlopi** [comment]
I will later to reproduce, but my guess given the error would be that you will have to somehow to await on `useDuckDB`.
