### ISSUE TITLE
preparedStatement.query: Do not know how to serialize a BigInt

### ISSUE THREAD

**Issue by rpbouman** [duckdb/duckdb-wasm#1563]
### What happens?

when passing a BigInt value (obtained from a resultset previously obtained by calling connection.query) to preparedStatement.query throws an error:  'Do not know how to serialize a BigInt'

### To Reproduce

```
      var columnName = 'bigintcolumn';
      var sql = `SELECT "${columnName}" AS "${columnName}" FROM (VALUES (CAST(1 AS BIGINT))) AS tab("${columnName}")`;
      var result = await connection.query(sql);
      var row = result.get(0);
      // value is BigInt 1n
      var value = row[columnName];

      sql += ` WHERE "${columnName}" = ?`;
      var stmt = await connection.prepare(sql);

      // following statement results in error: 'Do not know how to serialize a BigInt'
      result = await stmt.query(value);
```

### Browser/Environment:

Version 120.0.6099.130 (Official Build) (64-bit)

### Device:

Windows 11 Desktop

### DuckDB-Wasm Version:

1.28.0

### DuckDB-Wasm Deployment:

https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.28.0/+esm

### Full Name:

Roland Bouman

### Affiliation:

EPAM Systems BV Netherlands

**Comment by rpbouman** [comment]
From the perspective of a application using the duckdb WASM API, there is a similar issue with resultsets returning values coming from a column with a duckdb TIMESTAMP type.

The similarity is that TIMSTAMP values obtained from a resultset cannot be used directly as values for placeholders in a prepared statement. However, the error is different and I believe the cause is not serialization on the Arrow/Wasm site but in duckdb itself.

The error in this case is:

```
Error: Conversion Error: Unimplemented type for cast (TIMESTAMP -> DOUBLE)
    at ko.runPrepared (bindings_base.ts:301:19)
    at Qa.onMessage (worker_dispatcher.ts:189:51)
    at Ru.globalThis.onmessage (duckdb-browser-eh.worker.ts:29:19)
async_bindings.ts:150 Uncaught (in promise) Error: Conversion Error: Unimplemented type for cast (TIMESTAMP -> DOUBLE)
    at U.onMessage (async_bindings.ts:150:23)
```  

This error message is somewhat similar to when I do something like this in DuckDB directly:

`SELECT 1664562411000::TIMESTAMP`

My question is, what is the right way to file an issue for this one? It seems that the cause in this case does not have to do with serialization in the WASM api, but due to WASM attempting an casting operation that duckdb currently does not support.

According to this documentation (https://duckdb.org/docs/sql/data_types/typecasting) It looks like duckdb currently does not support any casting between any of the numeric types and TIMESTAMP, and personally I think it would make life easier if it did, and that would presumably also take care of this issue when using WASM.

Please let me know if and how you would like to go forward with this timestamp issue when using WASM and I can file the necessary issue reports along with proper repro paths.
