### ISSUE TITLE
Error on calling getTableNames for summarize query

### ISSUE THREAD

**Issue by aszenz** [duckdb/duckdb-wasm#1744]
### What happens?

Error: Binder Error: table "summarize_tbl" has 1 columns available but 26 columns specified
    at pa.getTableNames (bindings_base.ts:223:19)
    at Lo.onMessage (worker_dispatcher.ts:288:51)
    at Bc.globalThis.onmessage (duckdb-browser-eh.worker.ts:29:19)

### To Reproduce

`connection.getTableNames('summarize account')`;

### Browser/Environment:

Chromium Version 124.0.6367.201 (Official Build) (64-bit)

### Device:

Laptop

### DuckDB-Wasm Version:

^1.28.1-dev106.0

### DuckDB-Wasm Deployment:

_

### Full Name:

asrar

### Affiliation:

qbil

**Comment by carlopi** [comment]
Thanks for the bug report, could you possibly share a more complete snippet?
Thanks a lot
