### ISSUE TITLE
Error: INTERNAL Error: Unsupported compression function type

### ISSUE THREAD

**Issue by xelephas** [duckdb/duckdb-wasm#1781]
### What happens?

I am getting this error when running a simple `select` query on a user uploaded duckdb database file:

```
Error: INTERNAL Error: Unsupported compression function type
    at pa.runQuery (duckdb-browser-eh.worker.js:1:741917)
    at Lo.onMessage (duckdb-browser-eh.worker.js:1:729928)
    at Bc.globalThis.onmessage (duckdb-browser-eh.worker.js:1:763450)
@duckdb_duckdb-wasm.js?v=597ea27d:11971 Uncaught (in promise) Error: INTERNAL Error: Unsupported compression function type
    at O.onMessage (@duckdb_duckdb-wasm.js?v=597ea27d:11971:15)
```

### To Reproduce

```
 await db.registerFileHandle(
            "data_file.duckdb",
            file, // user uploaded file
            2,
            true
        );

const conn = await db.connect();
await conn.query("ATTACH 'data_file.duckdb'")
const arrowResult = await conn.query('select * from data_file.AAPL')
```

### Browser/Environment:

Chrome, Version 126.0.6478.127 (Official Build) (arm64)

### Device:

MacOS

### DuckDB-Wasm Version:

1.28.1-dev106.0

### DuckDB-Wasm Deployment:

Local development

### Full Name:

William Walker

### Affiliation:

Individual

**Comment by elsbrock** [comment]
Experiencing the same, but loading the file via `ATTACH 'https://...`. File can be opened just fine via `duckdb` CLI.

**Comment by elsbrock** [comment]
I think it depends on the bundle that was used. I changed it to the Vite approach, and I haven't seen those errors anymore.

**Comment by xelephas** [comment]
Thank you @carlopi for looking into this.

Here is the sample file:

https://file.io/PNwQR8qqgict

**Comment by marian-andre** [comment]
Hello ! I got the same behavior and the same error.
Unfortunately, I cannot share the `.duckdb` file
One hint from my side: if we use `force_compression=uncompressed`, no issue anymore. But it's not convenient for me as the file size to huge

**Comment by carlopi** [comment]
I assume this is now solved in the development branch, but for the fact that to enable ZSTD compression `parquet` needs to be explicitly loaded (but the error message should say so).

**Comment by carlopi** [comment]
I am closing, but do reopen if this happen to still be out.
