### ISSUE TITLE
Building from source fails in MacOS (it says missing JS files)

### ISSUE THREAD

**Issue by preddy4690** [duckdb/duckdb-wasm#1900]
### What happens?

I'm trying to build duckdb-wasm on my new MacOS. It gives an error when I run 'make serve' after running other commands. It can't find duckdb-mvp.js in ./src/bindings folder.

See attached screenshot.
![duckdb-wasm error](https://github.com/user-attachments/assets/e94d11fd-512c-461d-a3ef-a7541c1b09b9)

### To Reproduce

I ran these commands as instructed.

git clone https://github.com/duckdb/duckdb-wasm.git
cd duckdb-wasm
git submodule init
git submodule update
make apply_patches
make serve -- The error shows up here. 

### Browser/Environment:

Latest Chrome

### Device:

Macbook M3 Max

### DuckDB-Wasm Version:

1.29.0

### DuckDB-Wasm Deployment:

local

### Full Name:

Preetham Reddy

### Affiliation:

Tech Fabric

**Comment by carlopi** [comment]
Can you possibly try adding:
```
make wasm_relsize
```
before `make serve` ?

I need to check why this has not been caught and fix the Makefile, this is very likely on me having changed the Makefile. Thanks.

**Comment by neolord0** [comment]
I got the same results. 

"make serve" gave an error, but "make wasm_relsize" worked fine.

**Comment by pgarrison** [comment]
Copied from #2139:

> I am trying to build duckdb-wasm from source, on macOS. I am following these instructions from the README:
> ```
> git clone https://github.com/duckdb/duckdb-wasm.git
> cd duckdb-wasm
> git submodule init
> git submodule update
> make apply_patches
> make serve
> ```
> 
> In addition to those steps, I've installed `ccache` (from homebrew) and `emsdk` (from source).
> 
> My build is failing at `make serve` with the following error:
> ```
> Error: Command failed: sed -i.bak 's/require(["'\'']child_process["'\''])/["child_process"].map(require)/g' ./src/bindings/duckdb-mvp.js && rm ./src/bindings/duckdb-mvp.js.bak
> sed: ./src/bindings/duckdb-mvp.js: No such file or directory
> 
>     at genericNodeError (node:internal/errors:984:15)
>     at wrappedFn (node:internal/errors:538:14)
>     at checkExecSyncError (node:child_process:891:11)
>     at execSync (node:child_process:963:15)
>     at patchFile (file:///Users/philip.garrison/workspace/aics/duckdb-wasm/packages/duckdb-wasm/bundle.mjs:369:5)
>     at file:///Users/philip.garrison/workspace/aics/duckdb-wasm/packages/duckdb-wasm/bundle.mjs:104:5
>     at file:///Users/philip.garrison/workspace/aics/duckdb-wasm/packages/duckdb-wasm/bundle.mjs:359:3
>     at ModuleJob.run (node:internal/modules/esm/module_job:325:25)
>     at async ModuleLoader.import (node:internal/modules/esm/loader:606:24)
>     at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)
> ```
> I do have [duckdb-mvp.d.ts](https://github.com/duckdb/duckdb-wasm/blob/269b8d1d47886bff2257ff81856300192e39207e/packages/duckdb-wasm/src/bindings/duckdb-mvp.d.ts), but not `duckdb-mvp.js`. What should I do?

I was able to run `make wasm_relsize`, but `make serve` still fails with the same error.

**Comment by thesmartwon** [comment]
I get a different error running `make wasm_relsize`:
```sh
error: /opt/homebrew/Cellar/emscripten/4.0.21/libexec/src/postlibrary.js: undefined exported symbol: "createDyncallWrapper" in EXPORTED_RUNTIME_METHODS
Error: Aborting compilation due to previous errors
    at finalCombiner (file:///opt/homebrew/Cellar/emscripten/4.0.21/libexec/src/jsifier.mjs:887:13)
    at Module.runJSify (file:///opt/homebrew/Cellar/emscripten/4.0.21/libexec/src/jsifier.mjs:923:5)
    at file:///opt/homebrew/Cellar/emscripten/4.0.21/libexec/tools/compiler.mjs:108:17
em++: error: '/opt/homebrew/opt/node/bin/node /opt/homebrew/Cellar/emscripten/4.0.21/libexec/tools/compiler.mjs -' failed (returned 1)
```

Removing "createDyncallWrapper" from `-s EXPORTED_RUNTIME_METHODS=` in `lib/CMakeLists.txt` works.

**Comment by nraynaud** [comment]
https://github.com/emscripten-core/emscripten/pull/22825
it looks like the function `createDyncallWrapper ` has been removed altogether

**Comment by arjenpdevries** [comment]
I found this issue when trying to build DuckDB WASM from source following the instructions.

I have removed the `createDyncallWrapper` from the `CMakeLists.txt` as suggested in the [comment above](https://github.com/duckdb/duckdb-wasm/issues/1900#issuecomment-3668427157).

I then ran into the problem reported in [an older build problem issue](https://github.com/duckdb/duckdb-wasm/issues/2023#issuecomment-2888971758), where a `duckdb-mvp.js` file does not exist.

As suggested there, I have run `make wasm_dev`, which takes rather long but completes.

If I then do `make serve`, it fails on the problem that `./src/bindings/duckdb-coi.pthread.js` does not exist.

This seems similar to the problem with `duckdb-mvp.js` that had to be generated somehow, but I do not know how that happened when I ran `make wasm_dev`, so still stuck ;-(

(I also tried with `make wasm_relsize` instead of `make wasm_dev`, but to no avail.)

PS: the error I now get is:

```
sed: can't read ./src/bindings/duckdb-coi.pthread.js: No such file or directory
```

If I make that file (using `touch`), then compilation still fails. Right now, my hypothesis is that the version of `EMSDK` matters too - but I do not know which is the one expected. I am moving back in time from 5 to 4 to 3.1.56 (trying now, that number is mentioned in `actions/image/Dockerfile`).

Please advise!
I want to build from source because I want to enable multithreading in a next step...

**Comment by pgarrison** [comment]
In case it helps, there are some clues on build steps here: https://github.com/duckdb/duckdb-wasm/pull/2138#issuecomment-3676275651

**Comment by arjenpdevries** [comment]
Tnx @pgarrison trying a slightly older EMSDK now...

**Comment by arjenpdevries** [comment]
So... that helped!! 

Checked out from scratch and used EMSDK version `3.1.50`, did the `make apply_patches` (and an explicit `emcc --clear-cache`) before building with:

    WITH_WASM_THREADS=1 make -j 4 wasm_relsize
    WITH_WASM_THREADS=1 make serve

This sequence led to a successful build.

Except that loading the page served in Firefox does throw an error (in the console):
```
Uncaught (in promise) ReferenceError: getTempRet0 is not defined
    onMessage http://localhost:8080/static/js/351.8974eac4912f42c8d653.js:1
```

followed by a warning `The WebAssembly exception handling 'try' instruction is deprecated and should no longer be used. Please recompile to use the 'try_table' instruction instead.`.

The `make serve` command gives multiple warnings related to that same `getTempRet0` so that is probably related.

_PS: The comment by @pgarrison suggests `3.1.50`, later versions seem not to work correctly. This EMSDK is however not the same as the version specified in the `Dockerfile` in the `actions` directory, which is puzzling. My machine has FC43 instead of Ubuntu (used in the container), so that could explain the difference; but not sure._

**Comment by arjenpdevries** [comment]
Ok, revisiting the other thread https://github.com/duckdb/duckdb-wasm/issues/2023#issuecomment-2889060695 made me think to try EMSDK `3.1.69` which resolves every problem I had, and now both `make serve` and starting the shell in the served webpage seem to work. 

However, redoing everything from scratch, using EMSDK 3.1.69 fails to produce a build. So there seems to be still a weird interaction between versions, such that you can get an initial build to work with 3.1.50 and then fix the problem with the `GetTempRet0` function by upgrading the EMSDK to 3.1.69...

Overall, my conclusion is that I cannot build a working version from the repository and provided instructions, and definitely not in a reproducible manner. Hopefully the build system can be made more robust, but for now I will stop trying (especially since my goal was a multithreaded duckdb-wasm, which would challenge my devop skills just a little too much I'm afraid)...
