### ISSUE TITLE
examples/bare-node not working

### ISSUE THREAD

**Issue by nite** [duckdb/duckdb-wasm#1912]
### What happens?

The examples/bare-node example isnt working with node 22/23

### To Reproduce

Change the `Worker` import to 
```
const { Worker } = require('worker_threads');
```
and run 
```
 node .\node-duckdb.js
TypeError: this._worker.addEventListener is not a function
    at f.attach (...@duckdb\duckdb-wasm\dist\duckdb-node.cjs:1:13364)
    at new f (...\@duckdb\duckdb-wasm\dist\duckdb-node.cjs:1:13283)
    at ...node-duckdb.js:21:20
```

### Browser/Environment:

node 22/23

### Device:

windows (also tried ubuntu)

### DuckDB-Wasm Version:

1.29.0

### DuckDB-Wasm Deployment:

node

### Full Name:

Andrew Clancy

### Affiliation:

BMLL

**Comment by declann** [comment]
The code needs `web-worker` - I believe the API pattern for web workers versus node worker threads is different.

I think an issue here is that package.json doesn't refer to web-worker, so it isn't installed by npm install.

I got bare-node working by doing `npm i --save web-worker@1.4.1`

Note the version pinning: v1.5.0 of web-worker has a regression that I reported [here](https://github.com/developit/web-worker/issues/55)

Hopefully this points to a fix for you.

**Comment by lmdc45** [comment]
Also had to change to:

const worker = new Worker(path.relative(__dirname,DUCKDB_CONFIG.mainWorker));

as absolute path causing issues to load the Worker
