### ISSUE TITLE
Parquet remote URLs don't work in nodejs

### ISSUE THREAD

**Issue by aitskovi** [duckdb/duckdb-wasm#686]
I'm attempting to use duckdb-wasm from node (using the node-bare) example and running into an issue with it being unable to access web URLs (parquet files) as tables. Here's an example query & error message:

Query: `select * from 'https://shell.duckdb.org/data/tpch/0_01/parquet/orders.parquet' limit 10` 

```
Error: IO Error: No files found that match the pattern "https://shell.duckdb.org/data/tpch/0_01/parquet/orders.parquet"
    at rr.runQuery (/Users/aitskovi/Workspace/dsql/node_modules/@duckdb/duckdb-wasm/dist/duckdb-node-mvp.worker.cjs:3:65189)
    at Rf.onMessage (/Users/aitskovi/Workspace/dsql/node_modules/@duckdb/duckdb-wasm/dist/duckdb-node-mvp.worker.cjs:2:67390)
    at Tf.globalThis.onmessage (/Users/aitskovi/Workspace/dsql/node_modules/@duckdb/duckdb-wasm/dist/duckdb-node-mvp.worker.cjs:3:75554)
    at dispatchEvent (/Users/aitskovi/Workspace/dsql/node_modules/web-worker/cjs/node.js:37:32)
    at MessagePort.<anonymous> (/Users/aitskovi/Workspace/dsql/node_modules/web-worker/cjs/node.js:171:25)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
```

This query works correctly on shell.duckdb.org

Included below is a minimal reproduction (based on the node-bare example).

<details>
<summary>Reproduction information</summary>

node version: v16.13.1

package.json
```
{
  "name": "duckdb-example",
  "main": "index.js",
  "scripts": {
    "test": "node ./index.js"
  },
  "dependencies": {
    "@duckdb/duckdb-wasm": "^1.13.1-dev285.0",
    "web-worker": "^1.2.0"
  }
}
```

index.js (only modification is new query)
```
const duckdb = require('@duckdb/duckdb-wasm');
const path = require('path');
const Worker = require('web-worker');
const DUCKDB_DIST = path.dirname(require.resolve('@duckdb/duckdb-wasm'));

(async () => {
    try {
        const DUCKDB_CONFIG = await duckdb.selectBundle({
            mvp: {
                mainModule: path.resolve(DUCKDB_DIST, './duckdb-mvp.wasm'),
                mainWorker: path.resolve(DUCKDB_DIST, './duckdb-node-mvp.worker.cjs'),
            },
            eh: {
                mainModule: path.resolve(DUCKDB_DIST, './duckdb-eh.wasm'),
                mainWorker: path.resolve(DUCKDB_DIST, './duckdb-node-eh.worker.cjs'),
            },
        });

        const logger = new duckdb.ConsoleLogger();
        const worker = new Worker(DUCKDB_CONFIG.mainWorker);
        const db = new duckdb.AsyncDuckDB(logger, worker);
        await db.instantiate(DUCKDB_CONFIG.mainModule, DUCKDB_CONFIG.pthreadWorker);

        const conn = await db.connect();
        // const res = await conn.query(`SELECT count(*)::INTEGER as v FROM generate_series(0, 100) t(v)`);
        const res = await conn.query("select * from 'https://shell.duckdb.org/data/tpch/0_01/parquet/orders.parquet' limit 10")
        console.log(res.toString());

        await conn.close();
        await db.terminate();
        await worker.terminate();
    } catch (e) {
        console.error(e);
    }
})();
```
</details>

Is the web filesystem and native URL handling expected to be well supported when embedding duckdb-wasm in node?

**Comment by ankoh** [comment]
You are right @aitskovi yes that's expected.
The node version does not support reading from HTTP files today. 
It should be fairly easy to add, I can do this next week.
But please note that it's usually more desirable to use the native DuckDB version with node.js as DuckDB-Wasm is not multithreaded today and is bound to the wasm heap limits.

**Comment by aitskovi** [comment]
@ankoh Got it! And makes sense.

To confirm, I'm assuming that https://duckdb.org/docs/guides/import/http_import is supported on the node js version.

**Comment by aitskovi** [comment]
We're still in the prototyping phase for our usecase, so just looking for the shortest path to get something to play around with on our end.

**Comment by ankoh** [comment]
Yes, the node.js version is just a thin wrapper around DuckDB and also supports the HTTP extension.
Sounds good! Let us know if there's anything we can help with.
